//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MailTemplates {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MailTemplates() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI4.Resources.MailTemplates", typeof(MailTemplates).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you did not request this action, simply ignore this message.  Your account is safe..
        /// </summary>
        public static string Common_IfYouDidNotRequestThisAction {
            get {
                return ResourceManager.GetString("Common_IfYouDidNotRequestThisAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you need assistance, please contact us.
        /// </summary>
        public static string Common_IfYouNeedAssistanceContactUs {
            get {
                return ResourceManager.GetString("Common_IfYouNeedAssistanceContactUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi {0}.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Your Password.
        /// </summary>
        public static string PasswordReset_ResetYourPassword {
            get {
                return ResourceManager.GetString("PasswordReset_ResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string PasswordReset_ResetYourPasswordd {
            get {
                return ResourceManager.GetString("PasswordReset_ResetYourPasswordd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To reset your password, simply click on the link below or copy the link into the address bar of your browser:.
        /// </summary>
        public static string PasswordReset_ToResetYourPassword {
            get {
                return ResourceManager.GetString("PasswordReset_ToResetYourPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We are sending you message because there has been a request to reset the password in your &lt;b&gt;{0}&lt;/b&gt; account..
        /// </summary>
        public static string PasswordReset_WeAreSendingYouThisMessage {
            get {
                return ResourceManager.GetString("PasswordReset_WeAreSendingYouThisMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password:.
        /// </summary>
        public static string Registration_Password {
            get {
                return ResourceManager.GetString("Registration_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for registering to &lt;b&gt;{0}&lt;/b&gt;..
        /// </summary>
        public static string Registration_ThanksForRegistering {
            get {
                return ResourceManager.GetString("Registration_ThanksForRegistering", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name:.
        /// </summary>
        public static string Registration_UserName {
            get {
                return ResourceManager.GetString("Registration_UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have logged in using your Facebook account. However, you can also log in to {0} with the following credentials:.
        /// </summary>
        public static string Registration_YouHaveLoggedInUsingFacebook {
            get {
                return ResourceManager.GetString("Registration_YouHaveLoggedInUsingFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simply &lt;b&gt;&lt;a href=&quot;{0}&quot;&gt;click here&lt;/a&gt;&lt;/b&gt; and your account will be immediately activated.   This email expires in 5 days.
        ///&lt;br /&gt;
        ///Alternatively, you can copy the link below and paste it in your browser&apos;s address bar.&lt;br /&gt;&lt;br /&gt;{0}.
        /// </summary>
        public static string Verification_ClickHereToActivate {
            get {
                return ResourceManager.GetString("Verification_ClickHereToActivate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please confirm that this email address is associated to your newly created &lt;b&gt;{0}&lt;/b&gt; account..
        /// </summary>
        public static string Verification_PleaseConfirmEmail {
            get {
                return ResourceManager.GetString("Verification_PleaseConfirmEmail", resourceCulture);
            }
        }
    }
}
