//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Notifications {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Notifications() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI4.Resources.Notifications", typeof(Notifications).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been changed successfully..
        /// </summary>
        public static string ChangePasswordConfirmation {
            get {
                return ResourceManager.GetString("ChangePasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The url to retrieve your password has expired.  Please retrieve your password again..
        /// </summary>
        public static string InvalidPasswordRetrievalToken {
            get {
                return ResourceManager.GetString("InvalidPasswordRetrievalToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not find information for your user.  Please try again..
        /// </summary>
        public static string InvalidUser {
            get {
                return ResourceManager.GetString("InvalidUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We have sent you an email with a link to restore your password..
        /// </summary>
        public static string PasswordRetrievalConfirmation {
            get {
                return ResourceManager.GetString("PasswordRetrievalConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;h4&gt;Welcome to {0}&lt;/h4&gt;
        ///        &lt;p&gt;Please check your email, we just sent you a confirmation message.&lt;/p&gt;
        ///        &lt;p&gt;Just click on the link to validate your account and your account will be automatically validated.&lt;/p&gt;.
        /// </summary>
        public static string RegistrationConfirmation {
            get {
                return ResourceManager.GetString("RegistrationConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invitation to try {0}.
        /// </summary>
        public static string SubjectInvitationEmail {
            get {
                return ResourceManager.GetString("SubjectInvitationEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Password Reset request.
        /// </summary>
        public static string SubjectPasswordRetrievalEmail {
            get {
                return ResourceManager.GetString("SubjectPasswordRetrievalEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to {0}.
        /// </summary>
        public static string SubjectRegistrationEmail {
            get {
                return ResourceManager.GetString("SubjectRegistrationEmail", resourceCulture);
            }
        }
    }
}
