//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.237
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebUI4.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Referrals {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Referrals() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebUI4.Resources.Referrals", typeof(Referrals).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hi.
        /// </summary>
        public static string Hi {
            get {
                return ResourceManager.GetString("Hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I hope you enjoy it..
        /// </summary>
        public static string IHopeYouEnjoyIt {
            get {
                return ResourceManager.GetString("IHopeYouEnjoyIt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, the invitation has been sent.    Send another one!.
        /// </summary>
        public static string InvitationSent {
            get {
                return ResourceManager.GetString("InvitationSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your &lt;img src=&quot;http://media.altovientosolutions.com/dryicons/Handy%20Icons/24x24/user.png&quot; style=&quot;vertical-align:middle;&quot; alt=&quot;friends&quot;/&gt; friends to join {0}..
        /// </summary>
        public static string InviteYourFriends {
            get {
                return ResourceManager.GetString("InviteYourFriends", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite your friends via.
        /// </summary>
        public static string InviteYourFriendsVia {
            get {
                return ResourceManager.GetString("InviteYourFriendsVia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;p&gt;I have been using {0} and I thought you might like it.&lt;/p&gt;&lt;p&gt;Register and let me know what you think.&lt;/p&gt;.
        /// </summary>
        public static string IveBeenUsingXX {
            get {
                return ResourceManager.GetString("IveBeenUsingXX", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;a href=&quot;{0}&quot;&gt;Register here&lt;/a&gt; or simply copy this address in your browser: &lt;code&gt;{0}&lt;/code&gt;..
        /// </summary>
        public static string RegisterHere {
            get {
                return ResourceManager.GetString("RegisterHere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Invitation.
        /// </summary>
        public static string SendInvitation {
            get {
                return ResourceManager.GetString("SendInvitation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to When they join, you will get more  &lt;img src=&quot;http://media.altovientosolutions.com/dryicons/Handy%20Icons/24x24/star.png&quot; style=&quot;vertical-align:middle;&quot;/&gt; chances to win some of our prizes  &lt;img src=&quot;http://media.altovientosolutions.com/dryicons/Handy%20Icons/24x24/webcam.png&quot; style=&quot;vertical-align:middle;&quot; alt=&quot;prizes&quot;/&gt;.
        /// </summary>
        public static string WhenYouJoin {
            get {
                return ResourceManager.GetString("WhenYouJoin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your friend&apos;s email address.
        /// </summary>
        public static string YourFriendsEmailAddress {
            get {
                return ResourceManager.GetString("YourFriendsEmailAddress", resourceCulture);
            }
        }
    }
}
